### ISSUE TITLE
AverageFilterGPU3x3(...) crashes built Unity application

### ISSUE THREAD

**Issue by Kisa75** [PG649-3D-RPG/World-Generation#5]
When trying to use the World-Generator in a built Unity application, the scene using the generator is not able to load. The problem seems to be in the line:

``` kernelID = multiplyFilter ? computeShader.FindKernel("AverageFilterMultiply3x3") : computeShader.FindKernel("AverageFilterAdd3x3"); ```

For more information see the attached log file.

[log.txt](https://github.com/PG649-3D-RPG/World-Generation/files/10176778/log.txt)

**Comment by kb1t** [comment]
possible fix in c7ef973d7907573c03ae8a9c43a4ff3cefe05787
